#!/usr/bin/env bash
# Creating Redirection
sudo apt-get -y update && sudo apt-get install -y nginx
new="localhost;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;}"
sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
