#!/usr/bin/env bash
# a bash script to display text based on conditions

i=0;
while ((i < 10));
do
	if ((i == 3)); then
		echo "bad luck";
	elif ((i == 7)); then
		echo "good luck";
	else
		echo "Best School";
	fi
	((i++));
done
