#!/usr/bin/env bash
# a bash script to display time for 12hr and 59min

hr=0;
while ((hr <= 12));
do
	echo "Hour: $hr";
	min=1;
	while ((min <= 59));
	do
		echo "$min";
		((min++));
	done
	((hr++));
done
