#!/usr/bin/env bash
# a bash script to display file status

file_name="school"
if [ -e "$file_name" ]; then
	echo "$file_name file exists";
	if [ -s "$file_name" ]; then
		echo "$file_name file is not empty";
	else
		echo "$file_name file is empty";
	fi
	if [ -f "$file_name" ]; then
		echo "$file_name is a regular file";
	fi
else
	echo "$file_name file does not exist";
fi
